export const robots= [
    {
        id:1,
        name:'rebeka',
        username:'rebci',
        email:'rebeka@gmail.com'
    },
    {
        id:2,
        name:'johanna',
        username:'hanni',
        email:'johanna@gmail.com'
    },
    {
        id:3,
        name:'norbi',
        username:'tuc',
        email:'tuc@gmail.com'
    },
    {
        id:4,
        name:'alexa',
        username:'lexi',
        email:'kelaa@gmail.com'
    },
    {
        id:5,
        name:'alexa',
        username:'lexi',
        email:'kelaa@gmail.com'
    },
    {
        id:6,
        name:'alexa',
        username:'lexi',
        email:'kelaa@gmail.com'
    }
]